name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

          for file in $(find . -name "*.html" ! -name "404.html"); do
            page=$(echo $file | sed 's|./||')
            url="https://satoshigov.org/${page}"
            url=$(echo $url | sed 's/index.html//')
            echo "<url><loc>$url</loc></url>" >> sitemap.xml
          done

          echo '</urlset>' >> sitemap.xml

      - name: Commit sitemap
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto update sitemap" || echo "No changes"
          git push
